### ISSUE TITLE
Loading local libs or plugins

### ISSUE THREAD

**Issue by gabrielpage** [MiguelCastillo/Brackets-Ternific#44]
I'd like to be able to deliver a brackets folder to someone else who doesn't have my customer libs and plugins and let the .tern-project specify that these should be resolved from a different location.

Being able to use both project files and remote files would be extremely useful, at the moment, if I want to share a lib or plugin, I need to send my files, and have the other user put them into the extensions folder.

Something along the lines of :

{
  "libs": [
    "ecma5", "http://www.somehost.com/a_remote_lib", "${project}/a_project_lib"
  ]
  ,"plugins": {
    "http://www.somehost.com/a_remote_plugin" : {}, 
    "${project}/a_project_plugin" : {}
  }
}

**Comment by MiguelCastillo** [comment]
@gabrielpage I like the idea. It should be possible to do.  The only thing we will have some restrictions on is around CORS, which Ajax and importScript live by.

Libs would need to change because I am expecting them to be local. Here are both relevant parts of the code:
https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/LocalServer.js#L12
https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/LocalServer.js#L143

So I will need to add a small check to see if you are specifying a protocol or not... If you are, then I will need to build the url differently.  But this is not a hard change.

The same protocol check would need to happen.  Here is the relevant part of the code.
https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/TernWorker.js#L38

Now, I see that you have some `MACRO` type of project definition - `${project}`.  I am not sure what we can do about that.  If we were to put the macro expansion in ternific then you would need to define it in the .tern-project file itself.  I wouldn't want to rely on external data for that.  Or are you implying that project would be automatically expanded out to the current project's directory?

Would you be interested in PR?

**Comment by gabrielpage** [comment]
For ${project} I thought ternific would just replace it with ProjectManager.getProjectRoot()

This change is pretty trivial with a replace in the settings before you JSON.parse() but I didn't know if there was already a scheme for this.

Maybe the macro is not required, and another protocol specifier could be used project:///dir/somelib

But we'd need some way of being able to identify the lib should be found in the current folder rather than in the extensions folder. The other option would be to try to resolve it locally first, and only if it's not resolved look in the extensions folder, however, I think I'd prefer to be specific as it could be confusing.

For remote files, is there an option where the remote file is downloaded to the project onProjectLoad. This would get around CORS issues (but would mean we may have to overwrite something)

**Comment by MiguelCastillo** [comment]
I like the idea of expanding out ${project} to ProjectManager.getProjectRoot().  This can be done right [here](https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/Settings.js#L152) where we are processing the settings file.  Maybe we can just use lodash or mustache templates, both of which are provided by brackets.

As far as identifying if the file is from the the extension or some other location goes... I am not too sure quite yet.  The question I have for is...  How frequently do you load plugins/libs from your local project?

You really can't get around the CORS problem.  You either load the tern plugin via script tags or the server would need CORS support enabled, or possibly JSONP.  Loading via script tags is less of an option because currently tern is running in a web worker, which does not support script tags.  All files are loaded via `importScript`, which is affected by CORS.   I am inclined to make a change where CORS is a limitation.

**Comment by MiguelCastillo** [comment]
Actually, [this](https://github.com/MiguelCastillo/Brackets-Ternific/blob/master/Settings.js#L41) is a more appropriate place for handling templating.

**Comment by gabrielpage** [comment]
ok, I have the ${project} replacement working, let me tidy it up and I'll send a PR for that.

In fact, for extension vs other location, I think this will cover me. I don't see a need to be able to load from a location other than project or extensions.

I'm going to have a go at downloading the remote file directly into the folder. Once it's downloaded I can load using ${project} :)

**Comment by MiguelCastillo** [comment]
@gabrielpage yeah that sounds really good!  Thanks for your help on this :)

**Comment by MiguelCastillo** [comment]
merged in. thanks @gabrielpage !
