### ISSUE TITLE
cant use phaser's plugin

### ISSUE THREAD

**Issue by pooya72** [MiguelCastillo/Brackets-Ternific#69]
Hello i cant use [phaser's plugin](https://github.com/angelozerr/tern-phaser) with Ternific, may you help me in configurations

**Comment by MiguelCastillo** [comment]
@pooya72 so - I realize this is super late!  Just haven't had time for this project lately.  But I just made some changes to improve custom plugin support.

1. In order to get `phaser`, you need ternific v0.9.5 (which I just pushed out to the registry) or later.
2. Download the `phaser` plugin anywhere (I downloaded it to my project's folder)
3. Add the path to the .tern-project file.  Create one for your project if you haven't already.

This is what mine looks like

```
{
  "libs": [
    "{ternific}/libs/tern/defs/reserved",
    "{ternific}/libs/tern/defs/lodash",
    "browser",
    "chai",
    "ecma5",
    "ecma6",
    "browser",
    "jquery"
  ],
  "loadEagerly": [],
  "async": true,
  "plugins": {
    "modules": {},
    "requirejs": {},
    "doc_comment": {},
    "es_modules": true,
    "{project}/phaser": {}
  }
}
```

**Comment by MiguelCastillo** [comment]
https://github.com/MiguelCastillo/Brackets-Ternific/pull/87
