### ISSUE TITLE
Plugin installed globally

### ISSUE THREAD

**Issue by ficristo** [MiguelCastillo/Brackets-Ternific#77]
Does this extension read plugins installed globally? (`npm install -g ...`)
If it doesn't, is there a workaround?

**Comment by MiguelCastillo** [comment]
it uses a local npm package that I bundle. The integration with tern from a global package stand point isn't quite straight forward because brackets uses requirejs. There really isn't a workaround I can think of.  It's just the nature of the fact that installing an npm package globally is not a concept that requirejs handles, which is why I had to bundle it.  CJS with npm vs AMD.

**Comment by MiguelCastillo** [comment]
So, I read your message and commented specifically about the tern module itself.  I realize now that you are asking specifically about tern plugins.  So, it is possible to specify in your tern-project file a path for a plugin to load.  However, this is still expecting a UMD compliant bundle due to the same restriction I mentioned above regarding CJS (npm) vs AMD.

This thread goes over some of the details for including a custom plugin.  https://github.com/MiguelCastillo/Brackets-Ternific/issues/40

You would need to make the plugin is a UMD bundle so that brackets can load it.

**Comment by ficristo** [comment]
@MiguelCastillo Thank you for the answers.
I put the full path in the .tern-project file and now I don't see warnings anymore in the developer console.
For example: `/usr/local/lib/node_modules/tern-node-express/node-express": {}`
Still to see if they work correctly...
